# Generated by Django 4.2 on 2023-07-31 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knopki', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='CommandorFrame',
        ),
        migrations.AddField(
            model_name='user',
            name='frame',
            field=models.CharField(default='', max_length=100),
        ),
    ]
