# Generated by Django 4.2 on 2023-07-31 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knopki', '0002_command_delete_commandorframe_user_frame'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='masframe',
            field=models.CharField(default='', max_length=100),
        ),
    ]
