# Generated by Django 4.2 on 2023-08-07 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knopki', '0004_alter_command_command'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='messagefromuser',
            field=models.CharField(default='', max_length=100),
        ),
    ]
