# Generated by Django 4.2 on 2023-08-07 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knopki', '0005_command_messagefromuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='action',
            field=models.CharField(default='', max_length=100),
        ),
    ]
