# Generated by Django 4.2 on 2023-08-15 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knopki', '0007_command_helptext_command_name_functions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_id',
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
    ]
