# Generated by Django 4.2 on 2023-08-15 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knopki', '0009_message_element_text_element_button_element'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='message_element',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='knopki.message_element'),
        ),
    ]
