# Generated by Django 4.2.3 on 2023-08-15 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knopki', '0011_alter_command_action_alter_command_command_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='jopa_size',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
