# Generated by Django 4.2.3 on 2023-08-28 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knopki', '0014_command_waitmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='FIO',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='message_element',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='knopki.message_element'),
        ),
    ]
