# Generated by Django 4.2.3 on 2023-08-30 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knopki', '0015_user_fio_user_message_element'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='command',
            name='waitmessage',
        ),
        migrations.AddField(
            model_name='user',
            name='waitmessage',
            field=models.BooleanField(default=False),
        ),
    ]
