# Generated by Django 4.2.3 on 2023-08-30 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knopki', '0016_remove_command_waitmessage_user_waitmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='frame',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
