# Generated by Django 4.2.3 on 2023-08-30 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knopki', '0017_alter_user_frame'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
