# Generated by Django 4.2.3 on 2023-08-30 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knopki', '0018_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(blank=True, default='', max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='usernick',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
