# Generated by Django 4.2.3 on 2023-08-30 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knopki', '0021_adminrole_message_element'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminrole',
            name='frame',
        ),
        migrations.RemoveField(
            model_name='adminrole',
            name='waitmessage',
        ),
    ]
