# Generated by Django 4.2.3 on 2023-09-04 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knopki', '0023_adminrole_button_element'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminrole',
            name='adminhandler',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='обработчик'),
        ),
    ]
