# Generated by Django 4.2.3 on 2023-09-04 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knopki', '0024_adminrole_adminhandler'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminrole',
            name='adminhandler',
        ),
        migrations.AddField(
            model_name='message_element',
            name='adminhandler',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='обработчик'),
        ),
    ]
