# Generated by Django 4.2.3 on 2023-09-04 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knopki', '0025_remove_adminrole_adminhandler_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message_element',
            name='dopaction',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='обработчик'),
        ),
        migrations.AddField(
            model_name='message_element',
            name='dophandler',
            field=models.BooleanField(default=False),
        ),
    ]
