# Generated by Django 4.2.3 on 2023-09-04 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knopki', '0026_message_element_dopaction_message_element_dophandler'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message_element',
            name='adminhandler',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='админобработчик'),
        ),
        migrations.AlterField(
            model_name='message_element',
            name='dopaction',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Доп.команды'),
        ),
    ]
