# Generated by Django 4.2.3 on 2023-09-04 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knopki', '0027_alter_message_element_adminhandler_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message_element',
            name='dopaction',
            field=models.TextField(blank=True, default=None, max_length=255, null=True, verbose_name='Доп.команды'),
        ),
    ]
