# Generated by Django 4.2.3 on 2023-09-05 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knopki', '0028_alter_message_element_dopaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='message_element',
            name='deletewait',
            field=models.BooleanField(default=False),
        ),
    ]
